server:
  port: 8081
spring:
  jpa:
    #    应用启动时是否自动建表，默认false
    generate-ddl: true
    #    是否在控制台显示sql语句
    show-sql: true
    #    设置应用启动时不重新建表
    hibernate:
      ddl-auto: none
  #      配置数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpptest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
logging:
  #  设置日志输出格式
  pattern:
    console: level-%level %msg%n
  level:
    root: info #springboot启动时的日志级别
    org.hibernate: info #hibernate运行日志级别
    #    在show_sql为true时设置sql中的动态参数
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    #    在show_sql为true时显示查询结果
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    #    控制自己的代码运行时显示的日志级别
    com.kaikeba.provider: debug
