server:
  port: 9999
#  指定当前工程远程库git地址
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:jpp-ssx/departConfig.git
#          username: jpp-ssx
#          password: 1992jpp521521
